services:
- type: web
  name: lego-collector
  runtime: python
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn server:app
  envVars:
  - key: BRICKSET_API_KEY
    sync: false
